# Generated by Django 6.1.1 on 2026-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "delivery_id",
                    models.CharField(
                        help_text="GitHub's X-GitHub-Delivery GUID; the idempotency key.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "event",
                    models.CharField(db_index=True, help_text="X-GitHub-Event.", max_length=64),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="payload.action, when the event has one.",
                        max_length=64,
                    ),
                ),
                ("repo_full_name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("sender", models.CharField(blank=True, max_length=255)),
                (
                    "hook_id",
                    models.CharField(blank=True, help_text="X-GitHub-Hook-ID.", max_length=64),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("payload", models.JSONField()),
            ],
            options={
                "ordering": ("-received_at",),
                "indexes": [
                    models.Index(
                        fields=["repo_full_name", "event", "-received_at"],
                        name="webhooks_we_repo_fu_c58d8f_idx",
                    )
                ],
            },
        ),
    ]
